"""recording watch tracking

Revision ID: rec0watch7m7a
Revises: a1f7c3e9b2d4
Create Date: 2026-06-20 22:24:25.116680
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'rec0watch7m7a'
down_revision: Union[str, None] = 'a1f7c3e9b2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('zoom_uuid', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('last_position_secs', sa.Float(), nullable=False),
    sa.Column('max_position_secs', sa.Float(), nullable=False),
    sa.Column('watched_segments', sa.JSON(), nullable=False),
    sa.Column('duration_secs', sa.Float(), nullable=False),
    sa.Column('percent_complete', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zoom_uuid', 'user_id', name='uq_watch_progress_identity')
    )
    op.create_index(op.f('ix_watch_progress_user_id'), 'watch_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_watch_progress_zoom_uuid'), 'watch_progress', ['zoom_uuid'], unique=False)
    op.add_column('meetings', sa.Column('recording_s3_key', sa.String(length=512), nullable=True))
    op.add_column('meetings', sa.Column('recording_status', sa.String(length=16), nullable=False, server_default="none"))
    op.add_column('meetings', sa.Column('recording_duration_secs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'recording_duration_secs')
    op.drop_column('meetings', 'recording_status')
    op.drop_column('meetings', 'recording_s3_key')
    op.drop_index(op.f('ix_watch_progress_zoom_uuid'), table_name='watch_progress')
    op.drop_index(op.f('ix_watch_progress_user_id'), table_name='watch_progress')
    op.drop_table('watch_progress')
    # ### end Alembic commands ###
